language: go

before_install:
  - mv ../../CloudAutomationSolutions ../../cloudautomationsolutions
  - go get -u github.com/Masterminds/glide
  - glide install --strip-vendor

script: go test ./... && go build .

go:
  - "1.10"
